DSSurvey %>% 
  
  select(-starts_with("ID")) %>% 
  
  slice(-1:-2) -> 
  
  DSSurvey

DSSurvey$index <- 1:nrow(DSSurvey)
DSSurvey %>% 
  select(index, everything()) ->
  DSSurvey

logical_cols <- c("Autism",
                  "DiagnosesPHY_AcidReflux", 
                  "DiagnosesPHY_AirwayMalacia",
                  "DiagnosesPHY_Alopecia",
                  "DiagnosesPHY_AlzheimersDementia",
                  "DiagnosesPHY_AtlantoaxialInstability",
                  "DiagnosesPHY_Celiac", 
                  "DiagnosesPHY_ChronicEarInfection", 
                  "DiagnosesPHY_CHD",
                  "DiagnosesPHY_Diabetes",
                  "DiagnosesPHY_DSArthropathy",
                  "DiagnosesPHY_Duodenalatresia",
                  "DiagnosesPHY_Folliculitis",
                  "DiagnosesPHY_FrequentRespiratoryInfections",
                  "DiagnosesPHY_Hashimotos",
                  "DiagnosesPHY_HearingLoss",
                  "DiagnosesPHY_Hirschsprungs",
                  "DiagnosesPHY_Hypertension",
                  "DiagnosesPHY_Hypothyroidism",
                  "DiagnosesPHY_IronDeficiency",
                  "DiagnosesPHY_LactoseIntolerance",
                  "DiagnosesPHY_Leukemia",
                  "DiagnosesPHY_OtitisMedia",
                  "DiagnosesPHY_PulmonaryHypertension",
                  "DiagnosesPHY_SleepApnea",
                  "DiagnosesPHY_SwallowingFeedingDifficulty",
                  "DiagnosesPHY_TransientLeukemia",
                  "DiagnosesPHY_VisionImpairment",
                  "Regression", 
                  "Regression_Catatonia",
                  "Regression_LossAbilityDressSelf",
                  "Regression_LossAbilityReadWrite",
                  "Regression_LossAbilityInteractSocially",
                  "Regression_LossAbilityAttendSchool",
                  "Regression_LossAbilityAttendDailyProgram",
                  "Regression_LossAbilitySelfCare",
                  "Therapy_Physical",
                  "Therapy_Occupational",
                  "Therapy_Feeding",
                  "Therapy_Speech",
                  "Therapy_Music",
                  "Therapy_Horse",
                  "DiagnosesMEN_Anxiety",
                  "DiagnosesMEN_Bipolar",
                  "DiagnosesMEN_Depression",
                  "DiagnosesMEN_OCD",
                  "DiagnosesMEN_Schizophrenia",
                  "AlcoholSubstanceAbuse",
                  "AlcoholSubstanceAbuse_Other",
                  "ClinicVisits", 
                  "Clinic_Developmental_Use",
                  "Clinic_Developmental_Want",
                  "Clinic_Dietician_Use",
                  "Clinic_Dietician_Want",
                  "Clinic_EducationalAdvocate_Want",
                  "Clinic_Financial_Use",
                  "Clinic_Financial_Want",
                  "Clinic_GeneticCounselor_Use",
                  "Clinic_GeneticCounselor_Want",
                  "Clinic_MentalServices_Use",
                  "Clinic_MentalServices_Want",
                  "Clinic_SocialWorker_Use",
                  "Clinic_SocialWorker_Want", 
                  "Clinic_Therapy_Use",
                  "Clinic_Therapy_Want",
                  "Clinic_DSstaff",
                  "Clinic2Visits", 
                  "Clinic_2_Developmental_Use",
                  "Clinic_2_Developmental_Want", 
                  "Clinic_2_Dietician_Use",
                  "Clinic_2_Dietician_Want",
                  "Clinic_2_EducationalAdvocate_Use",
                  "Clinic_2_EducationalAdvocate_Want",
                  "Clinic_2_Financial_Use",
                  "Clinic_2_Financial_Want",
                  "Clinic_2_GeneticCounselor_Use",
                  "Clinic_2_GeneticCounselor_Want",
                  "Clinic_2_MentalServices_Use",
                  "Clinic_2_MentalServices_Want",
                  "Clinic_2_SocialWorker_Use",
                  "Clinic_2_SocialWorker_Want",
                  "Clinic_2_Therapy_Use",
                  "Clinic_2_Therapy_Want",
                  "Clinic_2_DSstaff",
                  "Clinic3Visits",
                  "Clinic_3_Developmental_Use",
                  "Clinic_3_Developmental_Want",
                  "Clinic_3_Dietician_Use",
                  "Clinic_3_Dietician_Want",
                  "Clinic_3_EducationalAdvocate_Use",
                  "Clinic_3_EducationalAdvocate_Want",
                  "Clinic_3_Financial_Use",
                  "Clinic_3_Financial_Want",
                  "Clinic_3_GeneticCounselor_Use",
                  "Clinic_3_GeneticCounselor_Want",
                  "Clinic_3_MentalServices_Use",
                  "Clinic_3_MentalServices_Want",
                  "Clinic_3_SocialWorker_Use",
                  "Clinic_3_SocialWorker_Want",
                  "Clinic_3_Therapy_Use",
                  "Clinic_3_Therapy_Want",
                  "Clinic_3_DSstaff",)


all_that_apply_cols <- c("Prenatal_BloodTest",
                         "Prenatal_CVS",
                         "Prenatal_Amniocentesis",
                         "Prenatal_Ultrasound",
                         "Prenatal_NonstressTest",
                         "EducationDS_EarlyIntervention",
                         "EducationDS_Preschool",
                         "EducationDS_ElementarySchool",
                         "EducationDS_MiddleSchool",
                         "EducationDS_HighSchool",
                         "EducationDS_JobTraining",
                         "EducationDS_CollegeUniversity",
                         "No_ClinicServicesWanted_ApraxiaSpecialist",
                         "No_ClinicServicesWanted_Audiologist",
                         "No_ClinicServicesWanted_Behaviorist",
                         "No_ClinicServicesWanted_DevelopmentalSpecialist",
                         "No_ClinicServicesWanted_DieticianNutritionist",
                         "No_ClinicServicesWanted_EducationalAdvocate",
                         "No_ClinicServicesWanted_FeedingTherapist",
                         "No_ClinicServicesWanted_FinancialAdvisor",
                         "No_ClinicServicesWanted_GeneticCounselor",
                         "No_ClinicServicesWanted_Geneticist",
                         "No_ClinicServicesWanted_OccupationalTherapist",
                         "No_ClinicServicesWanted_Ophthalmologist",
                         "No_ClinicServicesWanted_PhysicalTherapist",
                         "No_ClinicServicesWanted_Psychiatrist",
                         "No_ClinicServicesWanted_Psychologist",
                         "No_ClinicServicesWanted_SocialWorker",
                         "No_ClinicServicesWanted_SLP")

factor_cols <- c("Relationship",
)

numeric_cols <- c("DiagnosesPHYage_AcidReflux",
                  "DiagnosesPHYage_AirwayMalacia",
                  "DiagnosesPHYage_Alopecia",
                  "DiagnosesPHYage_AlzheimersDementia",
                  "DiagnosesPHYage_AtlantoaxialInstability",
                  "DiagnosesPHYage_Celiac",
                  "DiagnosesPHYage_ChronicEarInfection",
                  "DiagnosesPHYage_CHD",
                  "DiagnosesPHYage_Diabetes",
                  "DiagnosesPHYage_DSArthropathy",
                  "DiagnosesPHYage_Duodenalatresia",
                  "DiagnosesPHYage_Folliculitis",
                  "DiagnosesPHYage_FrequentRespiratoryInfections",
                  "DiagnosesPHYage_Hashimotos",
                  "DiagnosesPHYage_HearingLoss",
                  "DiagnosesPHYage_Hirschsprungs",
                  "DiagnosesPHYage_Hypertension",
                  "DiagnosesPHYage_Hypothyroidism",
                  "DiagnosesPHYage_IronDeficiency",
                  "DiagnosesPHYage_LactoseIntolerance",
                  "DiagnosesPHYage_Leukemia",
                  "DiagnosesPHYage_OtitisMedia",
                  "DiagnosesPHYage_PulmonaryHypertension",
                  "DiagnosesPHYage_SleepApnea",
                  "DiagnosesPHYage_SwallowingFeedingDifficulty",
                  "DiagnosesPHYage_TransientLeukemia",
                  "DiagnosesPHYage_VisionImpairment",
                  "Hospitalizations",
                  "HospitalizationPlanned",
                  "HospitalizationUnplanned",
                  "ERVisits",
                  "Surgeries",
                  "Birth_year",
                  "Clinic_Age",
                  "Clinic_2_Age",
                  "Clinic_3_Age")

unsure_cols <- c("Premature",
                 "ConcernDiagnoses_1Highest",
                 "ConcernDiagnoses_2",
                 "ConcernDiagnoses_3 ",
                 "ConcernPotential_1Highest",
                 "ConcernPotential_2",
                 "ConcernPotential_3",
                 "ConcernSleepApnea")


DSSurvey %>% 
  mutate_at(factor_cols, as.factor) %>% 
  mutate_at(logical_cols, funs(if_else( . == "Yes", TRUE, FALSE)) ) %>% 
  mutate_at(numeric_cols, as.numeric ) %>%
  mutate_at(all_that_apply_cols, funs(if_else( is.na(.), FALSE, TRUE)) ) %>% 
  #mutate_at(unsure_cols, funs(if_else( . == "Yes", 
  #TRUE, 
  #if_else( . == "No", FALSE, NA))))->
  DSSurvey
